##  Plugin Information  ##
name: RuleBooks
version: version-number-unknown
main: net.syamn.rulebooks.RuleBooks
description: CraftBukkit RuleBooks Plugin
website: http://ci.sakura-server.net/
softdepend: [Vault]
##  Original Author     ##
author: syamn
commands:
    rulebooks:
      usage: /rulebooks - to see the help
      aliases: [rulebook, rb]
      description: To see the RuleBooks help.
permissions:
    rulebooks.*:
        default: op
        description: Allow access to all commands
        children:
            rulebooks.buy.*: true
            rulebooks.admin.*: true
    rulebooks.admin.*:
        default: op
        description: Allow access to admin commands
        children:
            rulebooks.admin.new: true
            rulebooks.admin.delete: true
            rulebooks.admin.cost: true
            rulebooks.admin.list: true
            rulebooks.admin.reload: true
    rulebooks.buy.*:
        default: op
        description: Allow to buy all rulebooks
    rulebooks.admin.new:
        default: op
        description: Allow to use new command
    rulebooks.admin.delete:
        default: op
        description: Allow to use delete command
    rulebooks.admin.cost:
        default: op
        description: Allow to use cost command
    rulebooks.admin.list:
        default: op
        description: Allow to use list command
    rulebooks.admin.reload:
        default: op
        description: Allow to use reload command