# English RuleBooks File, Translated By: __

PermissionDenied: "&cYou don't have permission to use this!"
VaultDisabled: "&cEconomy links disabled on configuration!"
BookNotFound: "&cRulebook '%BOOK_NAME%' is not exist!"
NoBooks: "&cNo book found! Use '/rulebooks new <name>' to add a new one!"
NoAvailableBooks: "&cThere are no books available!"
AlreadyExist: "&cSame name book already exists!"
NotEnoughSlot: "&cNot enough empty slots in your inventory!"
NotEnoughMoney: "&cYou don't have enough money! (%COST%)"
InvalidPrice: "&cInvalid price: %COST%"
InvalidBookName: "&cInvalid book name: %BOOK_NAME%"
NotWrittenBook: "&cYou must hold a written book!"
Price: "Price"

AvailableListHeader: "&a ===== &bAvailable Rulebooks (%COUNT%) &a======"
AllListHeader: "&a ========== &bRuleBooks (%COUNT%) &a=========="

BoughtBook: "&aYou bought rulebook '%BOOK_NAME%' for %COST%!"
GotBook: "&aYou got rulebook '%BOOK_NAME%'!"
FirstJoin: "&aYou've received %COUNT% rule book(s)!"

NewBook: "&aRulebook '%BOOK_NAME%' saved!"
DeleteBook: "&aRuleBook '%BOOK_NAME%' deleted permanently!"

SetPrice: "&aSet price for rulebook '%BOOK_NAME%': %COST%"
Reloaded: "&aConfiguration reloaded!"